export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const FOLLOW_REQUEST = "FOLLOW_REQUEST";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_FAILURE = "FOLLOW_FAILURE";

export const SEARCH_PROFILES_REQUEST = "SEARCH_PROFILES_REQUEST";
export const SEARCH_PROFILES_SUCCESS = "SEARCH_PROFILES_SUCCESS";
export const SEARCH_PROFILES_FAILURE = "SEARCH_PROFILES_FAILURE";
